# print()
print("Alguma coisa")
print(3)
print(3 + 4)
print ("Olá" + " " + "Turma")

# input()
input("Digite seu nome: ")
print(input("Digite seu nome: "))
print("Olá, " + input("Digite seu nome: ") + "!")